#pragma once
#include <qdatetime.h>
#include <qimage.h>
#include <QRect>
#include <qpoint.h>
#include <qstring.h>
#include <QtWidgets/QDialog>
#include <QKeyEvent>
#include <qpainter.h>
#include <time.h>
#include <qstring.h>
#include <QtWidgets/QApplication>
#include <vector>
#include "GlobalDef.h"
#include "ENUM.h"
#include <cassert>
#include <qdebug.h>
#include <memory>
